export const items = [
    {
      key: "1",
      name: "Футбольный мяч",
      price: "2 500 ₽",
      city: "Калиниград",
      date: "Вчера в 09:15",
      picture: "img/items/football.jpg",
    },
    {
      key: "2",
      name: "Бутылка для воды (спортивная) ",
      price: "800 ₽",
      city: "Самара",
      date: "Вчера в 10:45",
      picture: "img/items/bottle.jpg",
    },
    {
      key: "3",
      name: "Книга 'Эго-твой враг'",
      price: "3 000 ₽",
      city: "Москва",
      date: "Сегодня в 07:30",
      picture: "img/items/book.jpg",
    },
    {
      key: "4",
      name: "Гитара новая",
      price: "12 000 ₽",
      city: "Москва",
      date: "Вчера в 12:45",
      picture: "img/items/guitar.jpg",
    },
    {
      key: "5",
      name: "Коврик для йоги",
      price: "1 500 ₽",
      city: "Калининград",
      date: "Вчера в 06:50",
      picture: "img/items/yoga_mat.jpg",
    },
    {
      key: "6",
      name: "Ipad 2 поколения",
      price: "9 000 ₽",
      city: "Челябинск",
      date: "Сегодня в 09:00",
      picture: "img/items/ipad.jpg",
    },
    {
      key: "7",
      name: "Кеды фирменные",
      price: "7 000 ₽",
      city: "Самара",
      date: "Вчера в 13:15",
      picture: "img/items/sneakers.jpg",
    },
    {
      key: "8",
      name: "Телевизор плазма",
      price: "34 000 ₽",
      city: "Москва",
      date: "Вчера в 10:30",
      picture: "img/items/tv.jpg",
    },
    {
      key: "9",
      name: "Золотисный ретривер вязка",
      price: "Бесплатно",
      city: "Самара",
      date: "Вчера в 10:45",
      picture: "img/items/dog.jpg",
    },
    {
      key: "10",
      name: "Наушники",
      price: "4 000 ₽",
      city: "Саратов",
      date: "Вчера в 14:20",
      picture: "img/items/headphones.jpg",
    },
    {
      key: "11",
      name: "Кружка handmade",
      price: "3 000 ₽",
      city: "Москва",
      date: "Вчера в 10:20",
      picture: "img/items/cup.jpg",
    },
    {
      key: "12",
      name: "Маска для сна",
      price: "500 ₽",
      city: "Калиниград",
      date: "Вчера в 10:40",
      picture: "img/items/mask.jpg",
    },
  ];